name: Run Rent Program

on:
  push:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write


jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run program
        run: python myHome.py

      - name: Commit updated data.json
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data.json
          git commit -m "Update data.json" || echo "No changes to commit"
          git push

          

